#!/bin/bash
#SBATCH --image=rootproject/root:6.28.04-ubuntu22.04
#SBATCH --account=m4287
#SBATCH --qos=shared
#SBATCH --tasks-per-node=1
#SBATCH --constraint=cpu
#SBATCH -t 4:00:00
#SBATCH -J Final_touches

working_dir=/global/cfs/cdirs/m4287/hep

for Process in ttbar  ztautau  wjets  htautau  diboson ;
do
{

input_dir=$working_dir/Delphes_PYTHIA8_output/csv_files_$Process
rm $input_dir/$Process.root 
shifter --image=rootproject/root:6.28.04-ubuntu22.04 hadd $input_dir/$Process.root $input_dir/*.root


shifter --image=rootproject/root:6.28.04-ubuntu22.04 python $working_dir/genHEPdata/scripts/process_counter.py $input_dir/$Process

# This script will merge the csv files generated by the FullDataGenerator into a single file.
shifter --image=nersc/fair_universe:1298f0a8 python3 $working_dir/genHEPdata/scripts/Data_merger.py --input $input_dir --output $working_dir/Delphes_PYTHIA8_output/Merged_files/$Process -p

}
done

shifter --image=nersc/fair_universe:1298f0a8 python3 Final_touches.py -i /global/cfs/cdirs/m4287/hep/Delphes_PYTHIA8_output/Merged_files/ -o /global/cfs/cdirs/m4287/hep/Delphes_PYTHIA8_output --input-format "parquet" --output-format "parquet"