
Process=$1
input_dir=$2
merged_dir=$3
working_dir=/global/cfs/cdirs/m4287/hep

# Pattern to match the ROOT files (e.g., *.root)
FILES="$input_dir/*.root"

# Output directory for the merged files
OUTPUT_DIR="$input_dir/merged_files"
mkdir -p "$OUTPUT_DIR"

# Number of files to merge per batch
BATCH_SIZE=1000

echo "Merging ROOT files in $input_dir"
echo "Output directory: $OUTPUT_DIR"
echo "Merging files in batches of $BATCH_SIZE"


# Initialize the batch counter
batch_num=1

file_list=$input_dir/file_name_list.txt

# ls $FILES > $file_list

# Loop over the files in batches of BATCH_SIZE
cat ${file_list} | xargs -n $BATCH_SIZE | while read -r file_list; do
    # Create the output file name for the current batch
    output_file="$OUTPUT_DIR/merged_${batch_num}.root"
    
    echo "Merging batch $batch_num into $output_file"

    # Run hadd to merge the current batch of files
    hadd -f "$output_file" $file_list
    
    # Increment the batch counter
    batch_num=$((batch_num + 1))
done

rm $input_dir/$Process.root
merged_file_list=$(ls -1 $OUTPUT_DIR/*.root)

hadd ${input_dir}/${Process}.root $merged_file_list

# This script will merge the csv files generated by the FullDataGenerator into a single file.

python3 $working_dir/genHEPdata/scripts/Data_merger.py --input $input_dir --output $merged_dir/$Process -p

python3 $working_dir/genHEPdata/scripts/process_counter.py $input_dir $merged_dir $Process
        