
Process=$1
input_dir=$2
merged_dir=$3

# Pattern to match the ROOT files (e.g., *.root)
FILES="$input_dir/*.root"

# Output directory for the merged files
OUTPUT_DIR="$input_dir/merged_files"
mkdir -p "$OUTPUT_DIR"

# Number of files to merge per batch
BATCH_SIZE=1000

# Initialize the batch counter
batch_num=1

# Loop over the files in batches of BATCH_SIZE
for ((i = 0; i < $(ls -1 $FILES | wc -l); i += BATCH_SIZE)); do
    # Create a list of files for the current batch
    file_list=$(ls -1 $FILES | sed -n "$((i + 1)),$((i + BATCH_SIZE))p")
    
    # Create the output file name for the current batch
    output_file="$OUTPUT_DIR/merged_${batch_num}.root"
    
    # Run hadd to merge the current batch of files
    hadd -f "$output_file" $file_list
    
    # Increment the batch counter
    batch_num=$((batch_num + 1))
done

rm $input_dir/$Process.root
hadd ${input_dir}/${Process}.root "$OUTPUT_DIR/merged_*.root"

# This script will merge the csv files generated by the FullDataGenerator into a single file.
python3 $working_dir/genHEPdata/scripts/Data_merger.py --input $input_dir --output $merged_dir/$Process -p

python3 $working_dir/genHEPdata/scripts/process_counter.py $input_dir $merged_dir $Process
        